
server:
  servlet:
    context-path: /text-stay-alive
  port: 8080
spring:
  application:
    name: TextStayAlive

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/db/text-stay-alive.db
